- hosts: 192.168.43.179
  tasks:
  - name: "Setup the docker Repository"
    yum_repository:
      name: "docker-ce"
      description: "This is my docker software repository"
      baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
      gpgcheck: no


  - name: "Download the Docker Software"
    package:
       name: "docker-ce-18.09.1-3.el7.x86_64"

  - name: "Start the Docker Engine"
    service:
     name: "docker" 
     state: restarted
     enabled: yes

  - name: "Install the Dependencies for the Docker Engine"
    command:
     cmd: "yum install python2 -y"

  - pip:
     name: docker-py


  - name: "Pull image from docker hub"
    docker_image:
            name: "httpd"
            source: pull

  - name: "Copy the Web content to the Docker Container "
    copy:
      dest: "/var/www/html/index.html"
      content: "This is my docker container website"

  - name: "create a docker container"
    docker_container:
       name: "webserver"
       image: "httpd"
       state: started
       exposed_ports: "80"
       ports: "8080:80"
       volumes: "/var/www/html/:/usr/local/apache2/htdocs"
       

