
- hosts: loadbalancer
  tasks:
  - name: "setup load balancer"
    package:
      name: "haproxy"
         

  - template:
      dest: "/etc/haproxy/haproxy.cfg"
      src: "haproxy.cfg.j2"

  - service:
      name: "haproxy"
      state: restarted

- hosts: aws_webserver
  tasks:

  - name: " Installing httpd software"
    package:
        name: "httpd"
        
  - name: "Installing php"
    package:
        name: "php"

  - copy:
        src: "index.php"
        dest: "/var/www/html/index.php"

  - name: " Stating httpd service"
    service:
        name: "httpd"
        state: started         
